export default {
  prettier: true,
  space: true,
  semicolon: false,
  rules: {
    "eol-last": "off",
    "@typescript-eslint/no-unsafe-assignment": "off",
    "unicorn/filename-case": "off",
    "n/prefer-global/process": "off",
    "@typescript-eslint/naming-convention": "off",
    "import/extensions": "off",
    "n/file-extension-in-import": "off",
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/ban-types": "off",
    "no-implicit-coercion": "off",
    "@typescript-eslint/prefer-nullish-coalescing": "off",
    "import/no-unassigned-import": "off",
    "unicorn/prevent-abbreviations": "off",
    "import/no-anonymous-default-export": "off",
    "unicorn/no-anonymous-default-export": "off",
    "unicorn/prefer-global-this": "off",
    "capitalized-comments": "off",
    "simple-import-sort/exports": "error",
    "simple-import-sort/imports": "error",
    "unicorn/numeric-separators-style": "off",
    "unicorn/prefer-module": "off",
    "import/no-named-as-default": "off",
    "unicorn/prefer-string-replace-all": "off",
    "max-nested-callbacks": ["error", 5],
    "import/order": "off",
    "new-cap": "off",
    indent: "off",
    "unicorn/catch-error-name": "off",
    camelcase: "warn",
    "react/prop-types": "off",
    "unicorn/prefer-switch": [
      "error",
      { minimumCases: 4, emptyDefaultCase: "do-nothing-comment" },
    ],
    "@stylistic/indent": "off",
    "@stylistic/comma-dangle": "off",
    "@stylistic/object-curly-spacing": "off",
    "@stylistic/semi": "off",
    "unicorn/no-empty-file": "warn",
    "prettier/prettier": [
      "error",
      {
        jsxSingleQuote: true,
        printWidth: 150,
        quoteProps: "as-needed",
        singleQuote: true,
        tabWidth: 2,
        trailingComma: "none",
        useTabs: false,
        semi: false,
      },
    ],
    "unicorn/no-array-reduce": "off",
    "unicorn/no-array-callback-reference": "off",
  },
  overrides: [
    // ✅ TypeScript + React support
    {
      files: ["**/*.ts", "**/*.tsx"],
      parser: "@typescript-eslint/parser",
      extends: [
        "xo",
        "xo-typescript",
        "plugin:react/recommended",
        "plugin:prettier/recommended",
      ],
    },
    // ✅ JavaScript + React support
    {
      files: ["**/*.js", "**/*.jsx"],
      extends: [
        "xo",
        "plugin:react/recommended",
        "plugin:prettier/recommended",
      ],
    },
    // ✅ Vitest & Jest support
    {
      files: [
        "**/*.test.js",
        "**/*.test.ts",
        "**/*.test.tsx",
        "**/*.spec.js",
        "**/*.spec.ts",
        "**/*.spec.tsx",
        "tests/**/*.{js,ts,tsx}",
      ],
      env: {
        jest: true,
        "vitest-globals/env": true,
      },
      plugins: ["vitest", "jest"],
      extends: ["plugin:vitest/recommended", "plugin:jest/recommended"],
      rules: {
        "max-nested-callbacks": "off",
        "unicorn/no-empty-file": "off",
        "no-unused-expressions": "off",
      },
    },
  ],
  settings: {
    react: {
      version: "detect",
    },
  },
};
